<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Model;

use CustomerValidation\Model\Base\CustomerValidationStatus as BaseCustomerValidationStatus;

/**
 * Class CustomerValidationStatus
 * @package CustomerValidation\Model
 */
class CustomerValidationStatus extends BaseCustomerValidationStatus
{
}
