<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Model;

use CustomerValidation\Model\Base\CustomerValidationStatusI18n as BaseCustomerValidationStatusI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class CustomerValidationStatusI18n
 * @package CustomerValidation\Model
 */
class CustomerValidationStatusI18n extends BaseCustomerValidationStatusI18n
{
    use I18nTimestampableTrait;
}
