<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Model;

use CustomerValidation\Model\Base\CustomerValidation as BaseCustomerValidation;

/**
 * Class CustomerValidation
 * @package CustomerValidation\Model
 */
class CustomerValidation extends BaseCustomerValidation
{
}
