<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Action;

use CustomerValidation\Action\Base\CustomerValidationStatusAction as  BaseCustomerValidationStatusAction;

/**
 * Class CustomerValidationStatusAction
 * @package CustomerValidation\Action
 */
class CustomerValidationStatusAction extends BaseCustomerValidationStatusAction
{
}
