<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Action;

use CustomerValidation\Action\Base\CustomerValidationAction as  BaseCustomerValidationAction;

/**
 * Class CustomerValidationAction
 * @package CustomerValidation\Action
 */
class CustomerValidationAction extends BaseCustomerValidationAction
{
}
