<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Type;

use CustomerValidation\Form\Type\Base\CustomerValidationIdType as BaseCustomerValidationIdType;

/**
 * Class CustomerValidation
 * @package CustomerValidation\Form
 */
class CustomerValidationIdType extends BaseCustomerValidationIdType
{
}
