<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Type;

use CustomerValidation\Form\Type\Base\CustomerValidationStatusIdType as BaseCustomerValidationStatusIdType;

/**
 * Class CustomerValidationStatus
 * @package CustomerValidation\Form
 */
class CustomerValidationStatusIdType extends BaseCustomerValidationStatusIdType
{
}
