<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event\Module\Base;

/**
 * Class CustomerValidationEvents
 * @package CustomerValidation\Event\Module\Base
 * @author TheliaStudio
 */
class CustomerValidationEvents
{
    const CUSTOMER_VALIDATION_CREATE = "action.customer_validation.create";
    const CUSTOMER_VALIDATION_UPDATE = "action.customer_validation.update";
    const CUSTOMER_VALIDATION_DELETE = "action.customer_validation.delete";
    const CUSTOMER_VALIDATION_STATUS_CREATE = "action.customer_validation_status.create";
    const CUSTOMER_VALIDATION_STATUS_UPDATE = "action.customer_validation_status.update";
    const CUSTOMER_VALIDATION_STATUS_DELETE = "action.customer_validation_status.delete";
}
