<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event;

use CustomerValidation\Event\Base\CustomerValidationStatusEvent as BaseCustomerValidationStatusEvent;

/**
 * Class CustomerValidationStatusEvent
 * @package CustomerValidation\Event
 */
class CustomerValidationStatusEvent extends BaseCustomerValidationStatusEvent
{
}
