<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event;

use CustomerValidation\Event\Base\CustomerValidationStatusEvents as BaseCustomerValidationStatusEvents;

/**
 * Class CustomerValidationStatusEvents
 * @package CustomerValidation\Event
 */
class CustomerValidationStatusEvents extends BaseCustomerValidationStatusEvents
{
}
