<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event;

use CustomerValidation\Event\Base\CustomerValidationEvents as BaseCustomerValidationEvents;

/**
 * Class CustomerValidationEvents
 * @package CustomerValidation\Event
 */
class CustomerValidationEvents extends BaseCustomerValidationEvents
{
}
