<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event;

use CustomerValidation\Event\Base\CustomerValidationEvent as BaseCustomerValidationEvent;

/**
 * Class CustomerValidationEvent
 * @package CustomerValidation\Event
 */
class CustomerValidationEvent extends BaseCustomerValidationEvent
{
}
