<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Base;

use CustomerValidation\Form\CustomerValidationStatusCreateForm as ChildCustomerValidationStatusCreateForm;
use CustomerValidation\Form\Type\CustomerValidationStatusIdType;

/**
 * Class CustomerValidationStatusForm
 * @package CustomerValidation\Form
 * @author TheliaStudio
 */
class CustomerValidationStatusUpdateForm extends ChildCustomerValidationStatusCreateForm
{
    const FORM_NAME = "customer_validation_status_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", CustomerValidationStatusIdType::TYPE_NAME)
        ;
    }
}
