<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Base;

use CustomerValidation\CustomerValidation;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class CustomerValidationCreateForm
 * @package CustomerValidation\Form\Base
 * @author TheliaStudio
 */
class CustomerValidationCreateForm extends BaseForm
{
    const FORM_NAME = "customer_validation_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addStatusField($translationKeys, $fieldsIdKeys);
    }

    protected function addStatusField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("status", "checkbox", array(
            "label" => $this->translator->trans($this->readKey("status", $translationKeys), [], CustomerValidation::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("status", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "status" => "customer_validation_status",
        );
    }
}
