<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Base;

use CustomerValidation\Form\CustomerValidationCreateForm as ChildCustomerValidationCreateForm;
use CustomerValidation\Form\Type\CustomerValidationIdType;

/**
 * Class CustomerValidationForm
 * @package CustomerValidation\Form
 * @author TheliaStudio
 */
class CustomerValidationUpdateForm extends ChildCustomerValidationCreateForm
{
    const FORM_NAME = "customer_validation_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", CustomerValidationIdType::TYPE_NAME)
        ;
    }
}
