<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Loop;

use CustomerValidation\Loop\Base\CustomerValidationStatus as BaseCustomerValidationStatusLoop;

/**
 * Class CustomerValidationStatus
 * @package CustomerValidation\Loop
 */
class CustomerValidationStatus extends BaseCustomerValidationStatusLoop
{
    /**
     * You may now add your own logic
     */
}
