<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Loop;

use CustomerValidation\Loop\Base\CustomerValidation as BaseCustomerValidationLoop;

/**
 * Class CustomerValidation
 * @package CustomerValidation\Loop
 */
class CustomerValidation extends BaseCustomerValidationLoop
{
    /**
     * You may now add your own logic
     */
}
