<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form;

use CustomerValidation\Form\Base\CustomerValidationStatusUpdateForm as BaseCustomerValidationStatusUpdateForm;

/**
 * Class CustomerValidationStatusUpdateForm
 * @package CustomerValidation\Form
 */
class CustomerValidationStatusUpdateForm extends BaseCustomerValidationStatusUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "code" => "code",
            "title" => "title",
            "description" => "description",
            "chapo" => "chapo",
            "postscriptum" => "postscriptum",
        );
    }
}
