<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event\Module;

use CustomerValidation\Event\Module\Base\CustomerValidationEvents as BaseCustomerValidationEvents;

/**
 * Class CustomerValidationEvents
 * @package CustomerValidation\Event\Module
 * @author TheliaStudio
 */
class CustomerValidationEvents extends BaseCustomerValidationEvents
{
}
