<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event\Base;

use Thelia\Core\Event\ActionEvent;
use CustomerValidation\Model\CustomerValidationStatus;

/**
* Class CustomerValidationStatusEvent
* @package CustomerValidation\Event\Base
* @author TheliaStudio
*/
class CustomerValidationStatusEvent extends ActionEvent
{
    protected $id;
    protected $code;
    protected $title;
    protected $description;
    protected $chapo;
    protected $postscriptum;
    protected $customerValidationStatus;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function getChapo()
    {
        return $this->chapo;
    }

    public function setChapo($chapo)
    {
        $this->chapo = $chapo;

        return $this;
    }

    public function getPostscriptum()
    {
        return $this->postscriptum;
    }

    public function setPostscriptum($postscriptum)
    {
        $this->postscriptum = $postscriptum;

        return $this;
    }

    public function getCustomerValidationStatus()
    {
        return $this->customerValidationStatus;
    }

    public function setCustomerValidationStatus(CustomerValidationStatus $customerValidationStatus)
    {
        $this->customerValidationStatus = $customerValidationStatus;

        return $this;
    }
}
