<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Event\Base;

use Thelia\Core\Event\ActionEvent;
use CustomerValidation\Model\CustomerValidation;

/**
* Class CustomerValidationEvent
* @package CustomerValidation\Event\Base
* @author TheliaStudio
*/
class CustomerValidationEvent extends ActionEvent
{
    protected $id;
    protected $status;
    protected $customerValidation;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    public function getCustomerValidation()
    {
        return $this->customerValidation;
    }

    public function setCustomerValidation(CustomerValidation $customerValidation)
    {
        $this->customerValidation = $customerValidation;

        return $this;
    }
}
