<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use CustomerValidation\Model\CustomerValidationQuery;

/**
 * Class CustomerValidation
 * @package CustomerValidation\Form\Base
 * @author TheliaStudio
 */
class CustomerValidationIdType extends AbstractIdType
{
    const TYPE_NAME = "customer_validation_id";

    protected function getQuery()
    {
        return new CustomerValidationQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
