<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Controller;

use CustomerValidation\Controller\Base\CustomerValidationStatusController as BaseCustomerValidationStatusController;

/**
 * Class CustomerValidationStatusController
 * @package CustomerValidation\Controller
 */
class CustomerValidationStatusController extends BaseCustomerValidationStatusController
{
}
