<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Controller;

use CustomerValidation\Controller\Base\CustomerValidationController as BaseCustomerValidationController;

/**
 * Class CustomerValidationController
 * @package CustomerValidation\Controller
 */
class CustomerValidationController extends BaseCustomerValidationController
{
}
