<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Action\Base;

use CustomerValidation\Model\Map\CustomerValidationTableMap;
use CustomerValidation\Event\CustomerValidationEvent;
use CustomerValidation\Event\CustomerValidationEvents;
use CustomerValidation\Model\CustomerValidationQuery;
use CustomerValidation\Model\CustomerValidation;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class CustomerValidationAction
 * @package CustomerValidation\Action
 * @author TheliaStudio
 */
class CustomerValidationAction extends BaseAction implements EventSubscriberInterface
{
    public function create(CustomerValidationEvent $event)
    {
        $this->createOrUpdate($event, new CustomerValidation());
    }

    public function update(CustomerValidationEvent $event)
    {
        $model = $this->getCustomerValidation($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(CustomerValidationEvent $event)
    {
        $this->getCustomerValidation($event)->delete();
    }

    protected function createOrUpdate(CustomerValidationEvent $event, CustomerValidation $model)
    {
        $con = Propel::getConnection(CustomerValidationTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $status = $event->getStatus()) {
                $model->setStatus($status);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setCustomerValidation($model);
    }

    protected function getCustomerValidation(CustomerValidationEvent $event)
    {
        $model = CustomerValidationQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'customer_validation' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            CustomerValidationEvents::CREATE => array("create", 128),
            CustomerValidationEvents::UPDATE => array("update", 128),
            CustomerValidationEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".customer_validation_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".customer_validation_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".customer_validation_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".customer_validation_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
