<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CustomerValidation\Action\Base;

use CustomerValidation\Model\Map\CustomerValidationStatusTableMap;
use CustomerValidation\Event\CustomerValidationStatusEvent;
use CustomerValidation\Event\CustomerValidationStatusEvents;
use CustomerValidation\Model\CustomerValidationStatusQuery;
use CustomerValidation\Model\CustomerValidationStatus;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class CustomerValidationStatusAction
 * @package CustomerValidation\Action
 * @author TheliaStudio
 */
class CustomerValidationStatusAction extends BaseAction implements EventSubscriberInterface
{
    public function create(CustomerValidationStatusEvent $event)
    {
        $this->createOrUpdate($event, new CustomerValidationStatus());
    }

    public function update(CustomerValidationStatusEvent $event)
    {
        $model = $this->getCustomerValidationStatus($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(CustomerValidationStatusEvent $event)
    {
        $this->getCustomerValidationStatus($event)->delete();
    }

    protected function createOrUpdate(CustomerValidationStatusEvent $event, CustomerValidationStatus $model)
    {
        $con = Propel::getConnection(CustomerValidationStatusTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            $model->setLocale($event->getLocale());

            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $code = $event->getCode()) {
                $model->setCode($code);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $description = $event->getDescription()) {
                $model->setDescription($description);
            }

            if (null !== $chapo = $event->getChapo()) {
                $model->setChapo($chapo);
            }

            if (null !== $postscriptum = $event->getPostscriptum()) {
                $model->setPostscriptum($postscriptum);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setCustomerValidationStatus($model);
    }

    protected function getCustomerValidationStatus(CustomerValidationStatusEvent $event)
    {
        $model = CustomerValidationStatusQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'customer_validation_status' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            CustomerValidationStatusEvents::CREATE => array("create", 128),
            CustomerValidationStatusEvents::UPDATE => array("update", 128),
            CustomerValidationStatusEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".customer_validation_status_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".customer_validation_status_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".customer_validation_status_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".customer_validation_status_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
